### ISSUE TITLE
Remove "Tags" from datasets

### ISSUE THREAD

**Issue by AntonyMilneQB** [kedro-org/kedro-viz#1092]
> **Note**. Good starter task for anyone wanting to get more familiar with kedro-viz!

Along similar lines to https://github.com/kedro-org/kedro-viz/issues/962...

Currently every single graph node on kedro-viz has a Tags field:
![image](https://user-images.githubusercontent.com/49395058/191797517-7c90b8cd-e6da-4766-affc-5ae37c7cc94a.png)

In reality, however, only kedro nodes can have tags. Datasets, transcoded datasets and parameters should not have this field.

1. Move `tags` from being a field in the base model `flowchart.GraphNode` to only in the kedro node model `flowchart.TaskNode`
2. Remove `tags` from instantiations of the non-`TaskNode` models, e.g. calls to `GraphNode.create_parameters_node` should no longer have a `tags` argument (you'll see it's currently just set to `set()` anyway)
3. Remove tags field from the frontend for everything but a task node

**Comment by rashidakanchwala** [comment]
qq - @AntonyMilneQB  -- what happens when you filter via tag ? should it show only the task nodes?

**Comment by AntonyMilneQB** [comment]
@rashidakanchwala very good question. I'm not sure... I think either current behaviour (where it shows all types of node) or just showing the task nodes would be fine. Probably the current behaviour is best, because then you can show/hide datasets separately using the toggle for that. But also that is quite inconsistent with the concept that tags apply to tasks only, since when you mouseover it highlights both the tasks and datasets that it will show. So overall I don't know. 🤔 I don't think it's a big problem either way (how many people use those show/hide toggles, especially now that tags aren't as important as they used to be?), but it's a great question and I'd be curious to hear your and others' thoughts on it!

**Comment by rashidakanchwala** [comment]
@AntonyMilneQB -- had a brief discussion with @tynandebold on this. the above suggested implementation to move tags from flowchart.GraphNode to flowchart.TaskNode is affecting the filtering as it's no longer showing any dependent datasets and maybe (subjective to users) showing an incomplete picture of the pipeline when u filter by tags. 

we also realised tags are not linked to modular pipelines, so in a collapsed mode - if you click on a tag within a modular pipeline -- it will say no data which is not expected behaviour. For the above 2, i think we need to create a separate ticket on how tag interactions work on FE and for this Tynan will also check on how much this feature is used. 

The main goal of this ticket is to remove the unnecessary tag information from metadata panel for datasets, and parameters and only have for task node. This can be easily achieved in the front-end (via isTaskNode show Tag other don't) without any change to BE. So maybe we just handle it that way for now. 

please let me know if the above makes sense. 


cc @Huongg

**Comment by tynandebold** [comment]
So it seems we're not tracking clicks on tags right now (maybe because they're dynamic?) but we are tracking filtering by the element types. Here's that data for over the past 90 days in an aggregate count (not unique):

<img width="1399" alt="image" src="https://user-images.githubusercontent.com/16869061/192533847-d2c6a8bf-28e9-430c-b5f7-671939f8da00.png">

Safe to say that it isn't used too much. 

Rashida, I agree with this part:

> The main goal of this ticket is to remove the unnecessary tag information from metadata panel for datasets, and parameters and only have for task node. This can be easily achieved in the front-end (via isTaskNode show Tag else don't) without any change to BE. So maybe we just handle it that way for now.

If we only do that it seems we should be safe and still solve the original issue created by Antony.

**Comment by AntonyMilneQB** [comment]
@rashidakanchwala thanks very much for the careful thought and explanation. That all sounds fine to me.

We should probably have a follow up ticket to see if we can also remove it from the backend without breaking the behaviour. Or at least understand how the tag selection code currently works to select dataset nodes, even though on the backend it's not (as far as I can tell at a glance) actually populated anywhere. Definitely the current frontend fix resolves the original issue here which is 99% of the problem. The 1% remaining feels like a small piece of tech debt, but it's not a big thing or high priority so happy to try and fix it another time or even just forget about it completely.
