### ISSUE TITLE
Kedro-viz needs too much to run properly

### ISSUE THREAD

**Issue by foxale** [kedro-org/kedro-viz#1159]
## Description

So according to this https://github.com/kedro-org/kedro-viz/issues/1125 kedro-viz requires 
- all plugins to be working (incl. mlflow connection to remote tracking server if leveraged)
- all python packages to be installed

For me it just doesn't make sense. Why would I need to have the python env ready to visualize project flow? The original issue seems dead, but kedro-viz is still in some way a core kedro feature, so..

**Comment by merelcht** [comment]
Transferred this issue to the Kedro-Viz repo, because it's not framework related.

**Comment by noklam** [comment]
> all plugins to be working (incl. mlflow connection to remote tracking server if leveraged)
> all python packages to be installed



@foxale Thank you for your question. The answer to that is pretty much covered. tl;dr
* Viz needs to load up the pipeline/nodes object, so the files would be loaded and the dependencies need to be installed. I don't see any way to get around it since you need to execute the code to get the Python representation of the pipeline.
* In most case - plugins aren't relevant, but as @deepyaman mentioned, the hook can actually change the DAG, so viz need to execute that. Otherwise, we can skip all the hooks and it would avoid the mlflow connection problem.

In theory, you could hide the dependencies so it won't be loaded, what viz need is just the pipeline & nodes objects.

**Comment by foxale** [comment]
Well, it still looks like a fixable problem on the `kedro-viz` side. One solution would be to add a parameter to kedro viz that would skip all import errors and `after_catalog_created` hooks and reder the "raw" DAG.

**Comment by noklam** [comment]
This is certainly doable if the team thinks we should do this. It's not the most elegant solution you can find, but I think simply

do something like
```python
if SOME_FLAG:
    session._hook_manager = _NullPluginManager()
# Before this line
context = session.load_context() 
```

This will remove all the hooks and should avoid this problem.

https://github.com/kedro-org/kedro-viz/blob/cc11edbec0777329eb66c875529ed35cfc5d7256/package/kedro_viz/integrations/kedro/data_loader.py#L72-L91

**Comment by astrojuanlu** [comment]
Potential solution for this: https://github.com/kedro-org/kedro-viz/issues/1459#issuecomment-1662165936

**Comment by rashidakanchwala** [comment]
Reopening this issue, as there's some issues around working with Spark that `--ignore--plugins` does no resolve

**Comment by ravi-kumar-pilla** [comment]
Hi @foxale , We implemented a possible solution [here](https://github.com/kedro-org/kedro-viz/pull/1966) which mocks missing dependencies. This will be merged in the upcoming Kedro-Viz release. 

I know it is a long overdue ticket, but it is finally ready :D . I hope this will resolve the dependency problems. Try running `kedro viz --lite` next time. Cheers !

**Comment by ravi-kumar-pilla** [comment]
Hi @foxale , Could you please let us know if you have used `kedro viz --lite` and was it helpful. Thank you
