### ISSUE TITLE
Investigate Collaborative Experiment Tracking on S3

### ISSUE THREAD

**Issue by rashidakanchwala** [kedro-org/kedro-viz#1269]
## Description

This ticket is to investigate saving/load experiment tracking data to S3. It is a part of Collaborative Experiment Tracking

**Comment by rashidakanchwala** [comment]
Ok, so we Huong and I tested saving/loading experiment tracking on S3 and it works really well. 

We also tried saving simultaneously unfortunately we were just microseconds away because our timestamp captures up till the 1000th microsecond. 

It is highly unlikely that two people will push to s3 at the same time. And s3 has it's own mechanisms to handle multiple read and write. 

Reading simultaneously worked fine and as expected we were only able to see runs that we created because runs list that is stored in sqlite.db is currently not shared. 

Next steps, we need to test the following:- 

- Upload sqlite.db to s3 for each user. 
- Read sqlite.db for all users and during  the reading we merge the databases so we can read data from every user in the same shared space. 

@idanov , @merelcht , @tynandebold , @AntonyMilneQB , @Huongg , @yetudada , @NeroOkwa , @jmholzer

**Comment by yetudada** [comment]
Woooo! This is fantastic work!

**Comment by AntonyMilneQB** [comment]
Thank you for the investigation @rashidakanchwala! When you say "saving/loading experiment tracking on S3", how are you actually doing this?
* for writing: do you save the sqlite db locally and then upload to s3 or somehow save to s3 directly?
* for reading: do you download the sqlite db locally and then read the local file or somehow read from s3 directly? 

While this might be a good stop-gap solution and is definitely worth exploring more I'm a bit sceptical how well it will work  ultimately. Or at least we need to work out exactly how the database merge works, how to make the solution scalable, how to make live updates work when you do a new run, etc. One thing I'm not concerned about is files being saved at the same time clashing though (we could just increase granularity of the timestamping or label according to the user who sent it).

I think @idanov had some scheme for sharing the sqlite database between many users to ensure eventual consistency which would mean there's only one "master copy" on s3 rather than needing to download many and merge them together. I never heard fully what the scheme actually was though - would be great if he could explain it more here.

**Comment by rashidakanchwala** [comment]
@AntonyMilneQB  -- so reading/writing just **tracking data** works fine by just making sure in the catalog you specify the s3 location. 

I had a discussion with @idanov and here is an overview 
- SQLite on S3 is just a file, we cannot treat it as a db or connect to it just like that (I am also going to test if this is possible anyway) 
- Ivan suggested having a SQlite shared space where every user in the project upload his/her own sqlite and every time they do a run. They will only append to thier sqlite DB. 

The only time we need to see all runs is when we read. So during the read functionality, we want to test if we can merge the dbs and show all runs or maybe we don't even need to merge. We just read multiple dbs through Kedro-viz and show all the data ...

**Comment by NeroOkwa** [comment]
This is amazing work! @rashidakanchwala. 
Thanks for the clarification on reading/writing the tracking data.

**Comment by rashidakanchwala** [comment]
Good News!!

Collaborative experiment tracking works! 

In our approach -- for each user we save their individual session_store.db in a shared folder on s3 and during read time, we read all the dbs from this shared folder and merge them to a single db. 

Huong, Tynan and I tested this, and below are screenshots of result

This is how it looks on s3 

![Image](https://user-images.githubusercontent.com/37628668/224025302-32709623-3cd3-46d4-9e91-a338a5ddc86f.png)

this is how it looks on Kedro-viz 


![Image](https://user-images.githubusercontent.com/37628668/224025855-1e839dc2-8818-4ef7-a5c9-f585a8989834.png)

**Comment by rashidakanchwala** [comment]
I am moving this investigation ticket to done for now as the POC has been tested and implementation has been agreed upon. I will create two new tickets 
- Build Collaborative Experiment Tracking feature - since we use fsspec, this will support s3 and other cloud services. 
- Test Collaborative Experiment Tracking - this is to test robustness of the feature on different platforms as well as stress test. 


For the first release we will support 
- reading all experiments from the cloud 
- modifying title, notes for different experiments but this is limited to only your own experiment tracking view. User's will not be able to view modifications to title/notes for different experiments by other users.
