### ISSUE TITLE
`MetricsDataSet._load` disappears after loading `line_magic` entry points if `kedro-viz` is installed

### ISSUE THREAD

**Issue by astrojuanlu** [kedro-org/kedro-viz#1352]
## Description
If Kedro Viz is installed, `MetricsDataSet._load` disappears after loading the `line_magic` entry points, giving way to the parent implementation from `JSONDataSet`, which behaves differently.

## Context
@b4rlw found this while actually trying to load a `MetricsDataSet`. The expected behavior was for the code to fail, but for him it was working when loading the `kedro.ipython` extension, which in turn calls `load_entry_points("line_magic")` here:

https://github.com/kedro-org/kedro/blob/2e70dec396567d2ba38456179aad0d4ae8e83b31/kedro/ipython/__init__.py#L108-L110

## Steps to Reproduce

It's kind of a contrived reproducer, but it works. It can probably be trimmed down, more debugging is needed to isolate the root cause.

```dockerfile
FROM ubuntu:22.04

RUN apt-get update && apt-get install -y curl git ca-certificates bzip2

RUN git clone https://github.com/b4rlw/metrics-test.git

WORKDIR /metrics-test

RUN curl micro.mamba.pm/install.sh | bash

RUN /root/.local/bin/micromamba env create -f conda-lock.yml -y -p ./.env

RUN /root/.local/bin/micromamba run -p ./.env poetry install
```

And then:

```
> docker run -it --rm --name metrics-test metrics-test:dev bash
# micromamba run -p ./.env/ ipython
...

In [1]: from kedro_datasets.tracking.metrics_dataset import MetricsDataSet

In [2]: MetricsDataSet._load
Out[2]: <function kedro_datasets.tracking.metrics_dataset.MetricsDataSet._load(self) -> NoReturn>

In [3]: import inspect

In [4]: from kedro.framework.cli import load_entry_points

In [5]: print(inspect.getsource(MetricsDataSet._load))
    def _load(self) -> NoReturn:
        raise DataSetError(f"Loading not supported for '{self.__class__.__name__}'")


In [6]: load_entry_points("line_magic")
Out[6]: [<function kedro_viz.launchers.jupyter.run_viz(port: int = None, local_ns: Dict[str, Any] = None) -> None>]

In [7]: print(inspect.getsource(MetricsDataSet._load))
    def _load(self) -> Any:
        load_path = get_filepath_str(self._get_load_path(), self._protocol)

        with self._fs.open(load_path, **self._fs_open_args_load) as fs_file:
            return json.load(fs_file)

```

However, if one uninstalls `kedro-viz`, this is the result:

```
In [1]: from kedro_datasets.tracking.metrics_dataset import MetricsDataSet

In [2]: import inspect

In [3]: from kedro.framework.cli import load_entry_points
...

In [4]: print(inspect.getsource(MetricsDataSet._load))
    def _load(self) -> NoReturn:
        raise DataSetError(f"Loading not supported for '{self.__class__.__name__}'")


In [5]: load_entry_points("line_magic")
Out[5]: []

In [6]: print(inspect.getsource(MetricsDataSet._load))
    def _load(self) -> NoReturn:
        raise DataSetError(f"Loading not supported for '{self.__class__.__name__}'")
```

## Expected Result
The class is not modified after loading the `line_magic` entry points when `kedro-viz` is installed.

## Your Environment

* Kedro version used (`pip show kedro` or `kedro -V`): 0.18.8
* kedro-datasets version used: 1.2.0
* Python version used (`python -V`): 3.10.10
* Operating system and version: Ubuntu 22.04

**Comment by antonymilne** [comment]
The peculiar behaviour here is really a result of kedro-viz rather than kedro, so I'm moving this to kedro-viz repo. But as above, I'm not sure what, if anything, we should do about it.

**Comment by astrojuanlu** [comment]
Thanks a lot for the detailed answer @antonymilne. Two points only:

As to why the user wanted to do this: "I was hoping to embed the metrics into a Streamlit dashboard when I came across this" https://www.linen.dev/s/kedro/t/11124459/i-am-facing-an-issue-where-a-metricsdataset-successfully-loa#478f6b26-d107-44da-a035-fdd6df7fde23 what could we offer for this use case? cc @b4rlw

As to what to do: When you say "eventually we will have some clarity over what MetricsDataSet._load should be in kedro-datasets" and "it's still not clear what the longer-term prospect of MetricsDataSet is", all I can think of is [this famous comment](https://stackoverflow.com/a/778275/554319) 😄 

```
// somedev1 -  6/7/02 Adding temporary tracking of Login screen
// somedev2 -  5/22/07 Temporary my ass
```

If `MetricsDataSet` is not intended for end users, could we define it in `kedro-viz` perhaps? Still does not avoid the monkeypatching (which I wish could disappear), but at least does not appear as a general purpose dataset (which is what I'd save `kedro-datasets` for)

**Comment by b4rlw** [comment]
I suppose there's nothing to stop me saving as both datasets. In my niche use case, I could keep the `MetricsDataSet` for Kedro Viz and use the `JSONDataSet` for my Streamlit dashboard. The down side is this will clutter up the DAG a little bit, but I can live with that!

Perhaps @astrojuanlu is right - if the functionality of the `MetricsDataSet` is (for the moment) intrinsically tied to Kedro Viz, perhaps it could live there instead.

**Comment by antonymilne** [comment]
I wouldn't say that `MetricsDataSet` wasn't intended for end users, just that it's not intended (yet) to be _loaded_ by an end user, because we haven't committed to exactly how that should work. We don't want people to start consuming a `MetricsDataSet` in a kedro pipeline other than writing to it as a final output, because if we later changed how `load` worked then it could break a lot of people's pipelines.

@b4rlw I would suggest continuing to use just `MetricsDataSet` and apply the same monkeypatching hack in your streamlit dashboard as we apply in kedro-viz, i.e. just copy and paste [these lines](https://github.com/kedro-org/kedro-viz/blob/918628d86ec210ea48d7d22bc29bacf1e144a0e3/package/kedro_viz/integrations/kedro/data_loader.py#L170) (or write your own `load_metrics_dataset` function that does what you need). You could even just `import kedro_viz.integrations.kedro.data_loader`, but pin the kedro-viz version to be on the safe side. It's ugly, but it will work perfectly well (it does in kedro-viz after all) and won't clutter your DAG at all.

In principle defining `MetricsDataSet` on kedro-viz would make _some_ sense for now, but ultimately experiment tracking should be consumable by tools other than kedro-viz and so I don't think this would make sense longer term. More practically, it would be a huge breaking change and almost definitely not worth the cost for a small benefit. So I'd rather that we solve the underlying issue by defining what `MetricsDataSet._load` _should_ do and keep it in kedro-datasets instead.

**Comment by antonymilne** [comment]
P.S. really the ideal solution here would be that you write your own dataset which implements the `load` method:
```
class MetricsDataSetWithLoad(MetricsDataSet):
    def _load(self):
        ...
```

And then use that in preference to `MetricsDataSet` in your catalog. This way you're not tied to our (non-)implementation of `MetricsDataSet` at all. But unfortunately this won't work for showing you the experiment tracking data in kedro-viz because the checks for dataset types are hardcoded to look for a class called `"tracking.MetricsDataSet"` and don't allowing for subclassing. This is something else I'd like to change, but it's not very high on the list of priorities because it's not a common requirement and the current solution just about works ok.

**Comment by b4rlw** [comment]
@antonymilne Thanks Antony, for the advice. For the time being I'll apply my own monkeypatch as you suggest!

**Comment by tynandebold** [comment]
Closing this as won't fix given @antonymilne's reasoning in the comments above.

**Comment by astrojuanlu** [comment]
> So I'd rather that we solve the underlying issue by defining what MetricsDataSet._load should do and keep it in kedro-datasets instead.

Is there an issue for this?

**Comment by tynandebold** [comment]
Not sure, that would be in the kedro repo.

**Comment by astrojuanlu** [comment]
Opened https://github.com/kedro-org/kedro/issues/2599
