### ISSUE TITLE
Update Kedro-Viz documentation for Collaborative Experiment Tracking

### ISSUE THREAD

**Issue by NeroOkwa** [kedro-org/kedro-viz#1353]
### Context
This is part of a wider collaborative experiment tracking product launch strategy [#74 ](https://github.com/kedro-org/kedro-devrel/issues/74). 

It tracks the update of the Kedro-Viz [section of the kedro documentation](https://docs.kedro.org/en/stable/visualisation/experiment_tracking.html) with the new collaborative experiment tracking feature [#1295](https://github.com/kedro-org/kedro-viz/issues/1295). 

### Goal
The goal is to provide a clear guide on how to use this feature.

**Comment by tynandebold** [comment]
For the initial release we'll focus on a blog post. The feature is rapidly changing, and while it's a WIP it's easier to publish/update blog posts, especially given the docs releases are tied to Kedro releases.

**Comment by NeroOkwa** [comment]
The action for this is covered in [#2589](https://github.com/kedro-org/kedro/pull/2589#event-9288867230).

**Comment by stichbury** [comment]
We have since discussed and decided against this approach since for user discoverability, all the information regarding experiment tracking in Kedro should be in one place, and the kedro framework docs is currently that single source of truth on Kedro. 

We will write the docs in the experiment tracking section in the kedro framework docs and note which version is applicable. There will be a blog post but there's a separate ticket for this in `kedro-devrel` https://github.com/kedro-org/kedro-devrel/issues/73
