### ISSUE TITLE
Version incompatibility between kedro-viz >4.6.0 and kedro 0.17.1

### ISSUE THREAD

**Issue by inigohidalgo** [kedro-org/kedro-viz#1361]
Hi,

I'm aware this is a bit of a strange issue, since I'm talking about such outdated versions at this point. But the other day I tried to update my kedro-viz to a later version to take advantage of some changes, but have found it impossible to upgrade because of incompatibilities with my kedro version which do not seem to be documented in the respective requirements.txt:

From v4.7.0 the following line is in `kedro_viz/launchers/cli.py`:
```python3
from kedro.framework.cli.project import PARAMS_ARG_HELP
```

This constant is not available in kedro 0.17.1 which causes viz not to launch. I'm not sure if there's any fix for this, but I wanted to raise it as it is a blocker for me upgrading my kedro-viz version using an old version of kedro, which unfortunately for the time being I am stuck with.

Thanks :)

**Comment by astrojuanlu** [comment]
Thanks for the bug report @inigohidalgo. Looks like an oversight:

https://github.com/kedro-org/kedro-viz/blob/ffa78774499da4ea93159a7a45d3a7d9c743a58a/package/requirements.txt#L2

**Comment by tynandebold** [comment]
`PARAMS_ARG_HELP` still exists in [Kedro framework](https://github.com/kedro-org/kedro/blob/3439e72ef9ef79095da35db88d0584e684299e09/kedro/framework/cli/project.py#L60) but is it no longer exposed?

@inigohidalgo curious why you're stuck with using an old version of Kedro?

**Comment by inigohidalgo** [comment]
Not too familiar with the implementation details, but the `PARAMS_ARG_HELP` constant in my project is in `src/project_name/cli.py` instead of the kedro package itself.

> curious why you're stuck with using an old version of Kedro?

We have some functionality which depends on manipulating the kedro context/session directly. That functionality was deprecated at some point through 0.17 so for the time being we are stuck. We're working on modifying this functionality to exploit hooks, but it's slow progress.

Anyways I'm not really asking for a fix or anything, since it's an old version of kedro, and we will probably be able to upgrade before year-end, but maybe somebody else will run into the same issue. Not sure if it's possible to retroactively limit the requirements for old versions of kedro-viz, though I do see the current version of kedro-viz still shows compatibility with >=0.17.0 which isn't accurate.

**Comment by inigohidalgo** [comment]
Also just to add that I don't think this is a new issue that's cropped up. I've been using kedro-viz 4.6.0 for over a year and a half, and only recently tried to upgrade it which brought the issue up.

**Comment by tynandebold** [comment]
Understood. Thank you for the details! We'll certainly update the compatibility requirement in the next release and point anyone else who has the same problem to this issue for reference.

**Comment by tynandebold** [comment]
We should also add a new section in our README that indicates which versions of Viz work with which version of Kedro. Let's put this in a table when we make this requirements change.

**Comment by antonymilne** [comment]
Argh, sorry about this! This is one of those occasions where what seemed like a very simple change was not actually that simple... The incompatibility here exists between `kedro-viz>=4.7` (due to https://github.com/kedro-org/kedro-viz/commit/fd84153c78942dea239ce4b9393be0dde431ec42) and `kedro<0.17.5` (due to https://github.com/kedro-org/kedro/commit/53000183f77a9278396d18ca548e1dee9c049a18). 

So I _think_ that if you `pip install kedro==0.17.5` (which is non-breaking since you're on 0.17.x already) then the latest kedro-viz should work ok for you.

We could try and fix this to maintain compatibility with kedro>=0.17.0, but given that you're the first person who has noticed this incompatibility I don't think there's huge call for it. So probably better to bump our requirement to `>=0.17.5` (assuming I'm right and it works ok).

**Comment by tynandebold** [comment]
PR is here: https://github.com/kedro-org/kedro-viz/pull/1366
