### ISSUE TITLE
Collaborative experiment tracking v3.0 - Sharing user modifications

### ISSUE THREAD

**Issue by rashidakanchwala** [kedro-org/kedro-viz#1371]
## Description
Currently, any modifications made by the user, such as changing the title, bookmarking, or adding notes, are not uploaded to the cloud storage. These modifications are local to the user's session_store on their local machine.

The purpose of this design ticket is to explore the best approach for enabling collaboration among users in modifying experiment metadata, including bookmarks, titles, and notes.

Some examples of different scenarios to consider include:

- Different users may want to bookmark different experiments. One possible solution is to provide two bookmark sections: "My Bookmarks" and "Shared Bookmarks" to accommodate individual preferences.
- Users may become confused if an experiment's title is changed by another user without their knowledge. For example, they may be searching for an experiment they named, only to find that another user has renamed it. 

There are other potential scenarios. So this ticket is to figure those and find an optimal solution. 

## Checklist

- [x] Include labels so that we can categorise your feature request

**Comment by tynandebold** [comment]
We'll reopen this ticket if we look at this again downstream.

**Comment by ChristopherRabotin** [comment]
Hi there,

Sorry to bump an old issue, but it seems that the notes are not shared between users. Specifically, in our team, we've set up kedro to store the session sqlite databases on S3, so that everyone can see other people's runs. However, the notes do not seem to be copied back on S3.

Here's how we tested this.
1. I ran a pipeline (via a Jupyter notebook which is why there is no run command here), then opened Kedro Viz, and wrote a note.

![image](https://github.com/user-attachments/assets/952b6db1-9519-4fc7-9486-95d5e02bbc48)

2. I closed kedro viz (ctrl+c)
3. A team member opened kedro viz on her machine, found that specific run and checked if there were any notes. In fact, the notes are not visible to her.

Is that by design or a config issue? 

Thanks

**Comment by rashidakanchwala** [comment]
Hi, this functionality had been planned but was not fully built because we did not see much user demand at the time.
I'm looping in @astrojuanlu (our PM) to review your request and to determine if and when we might be able to implement it.
Thanks for your feedback and will keep you updated on any progress.

**Comment by astrojuanlu** [comment]
Hi @ChristopherRabotin, good to see you here!

Experiment Tracking in Kedro-Viz is in maintenance mode, it's not in our roadmap to add more features.

However, you could help us understand a bit whether we should change that - have you evaluated alternative solutions like MLflow or similar?

**Comment by ChristopherRabotin** [comment]
Hi Juan! It sure is a small world.

We haven't looked into alternatives yet. Our infrastructure is very much of a local machine approach because we need to collaborate between different companies, and our respective devops teams are too busy on other stuff to provide any support.

I'm surprised to hear that Kedro Viz is in maintenance mode. Hypothetically, if I were to implement that change, could it be reviewed and released, or are new features even from other contributors on pause for now?

Cheers

**Comment by astrojuanlu** [comment]
> We haven't looked into alternatives yet. Our infrastructure is very much of a local machine approach because we need to collaborate between different companies, and our respective devops teams are too busy on other stuff to provide any support.

Thanks for the context. I'd recommend you to check out MLflow, works well in a local setting, is well integrated with Kedro, and is more sophisticated than what Kedro-Viz currently provides https://docs.kedro.org/en/latest/integrations/mlflow.html

> Hypothetically, if I were to implement that change, could it be reviewed and released, or are new features even from other contributors on pause for now?

I'd like to say "yes" but the truth is that we'd have to maintain it ourselves and it would steal some attention from the priorities we have now, so in principle we are not taking such contributions until we decide what to do with the feature, sorry!
