### ISSUE TITLE
[Spike] Clarifying Overlap: Pydantic Models vs. Data Classes in Backend

### ISSUE THREAD

**Issue by rashidakanchwala** [kedro-org/kedro-viz#1538]
## Description

We recently had a look at our backend structure while reviewing the Shareable Viz PR, we realised that using both Pydantic Base Models and data classes in our backend might be unnecessary. This ticket is to investigate this issue and refactor the code accordingly.

## Context:

FastAPI's documentation recommends the use of Pydantic for [input validation and data serialization](https://fastapi.tiangolo.com/tutorial/body/). It mentions [data classes](https://fastapi.tiangolo.com/advanced/dataclasses/) offering a more advanced approach. Using both Pydantic models and data classes for similar purposes has lead to redundancy and has caused issues with mypy 1.0.

In this issue; we want to understand the below:-
- Are there performance implications between the two? If one is more efficient than the other for specific tasks, we should clarify their roles. Was the decision to use both related to our data access manager and repositories?
- Given that Pydantic models are classes as well, can't we achieve similar functionalities with them as with data classes?

## Checklist

- [x] Include labels so that we can categorise your feature request

**Comment by antonymilne** [comment]
Some more context and notes - sorry for the delay in writing this up!

When it comes to handling the responses, this is where things stand now:
* FastAPI responses live in api/rest/responses.py and uses pydantic `BaseModel`
* underlying data model lives in models/flowchart.py and uses `dataclass`

I definitely think it's a good move to convert the data model to use `BaseModel` as well.

Why should these things be separate in the first place? [This gives some good principles](https://tyk.io/blog/your-data-model-is-not-an-api/), although in our case much of it is not relevant. In practice, for us, the main distinction between the data model and the API responses will be that the responses must be JSON serialisable while the data model can have arbitrary objects in it (e.g. an `AbstractDataSet`).

But the responses and data model will be very similar in kedro-viz, so while they should remain distinct there should be a good way to write them without just copying and pasting code. You should definitely read [this page](https://fastapi.tiangolo.com/tutorial/response-model/) to understand the different options. Basically for us I think there's 3 options:
1. subclass. This is a conventional way to handle things and generally a good plan. In our case though note that you need to be careful about getting the hierarchy correct since we want the API to depend on the data model and not vice versa. This is possible but potentially a bit awkward because inheritance makes it easy to add fields but not to remove them.
2. if all that's different between data model and response is removing fields then [`response_model_exclude/include`](https://fastapi.tiangolo.com/tutorial/response-model/#response_model_include-and-response_model_exclude) would be a very easy way to handle it. In general this is not a recommended approach but for us actually I think it would be fine and maybe the clearest way
3. make the fields that should be excluded from the response private: https://github.com/tiangolo/fastapi/issues/1378

Overall I would start with one of the models (e.g. `GraphNodeMetadata` and its subclasses) and briefly prototype all three approaches to get a feel for which one will be best, and then roll out that to all the other models in the file.

Just so it doesn't get forgotten: `TrackingDatasetModel` in experiment_tracking.py should also be converted to pydantic.
