### ISSUE TITLE
Resolve Python dependency PRs

### ISSUE THREAD

**Issue by tynandebold** [kedro-org/kedro-viz#1582]
## Description

We have a number of open dependabot PRs that we should resolve. They are:

- [x] #1483 
- [x] #1518 
- [x] #1546 
- [x] #1547 
- [x] #1552 
- [x] #1561 

This issue should only be closed when all of those PRs are closed, either by merging and accepting the update or closing them because they're not needed.

## Checklist
- [x] Include labels so that we can categorise your issue

**Comment by astrojuanlu** [comment]
Comment from the peanut gallery: since Kedro-Viz dependabot is using the default configuration, `versioning-strategy` is set to `auto`, meaning 

> Try to differentiate between apps and libraries. Use `increase` for apps and `widen` for libraries.

https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#versioning-strategy

and since Kedro-Viz uses `requirements.txt` for its Python requirements, it's probably applying the `increase` strategy, which is arguably too aggressive for a component like Kedro-Viz. In fact, since Kedro switched to `pyproject.toml`, dependabot PRs have been using the `widen` strategy.

Viz can either

- Do nothing and keep aggressively upgrading dependencies, but this can lead to problems with people that have environments with lots of dependencies.
- Configure dependabot to use `widen`.
- Migrate dependencies to `pyproject.toml` #1527 and keep the `auto` config.

**Comment by tynandebold** [comment]
Thanks for the input. I think we'll go with your third bullet point above (Migrate dependencies to pyproject.toml). I've pulled that issue into this sprint now, so when that's done I hope these upgrades quiet down a bit.

**Comment by MehdiNV** [comment]
The `pyproject.toml` ticket may take a while due to its complexity, so going to progress this ticket forward so that it's not blocked
