### ISSUE TITLE
More flexible arrangement of nodes

### ISSUE THREAD

**Issue by astrojuanlu** [kedro-org/kedro-viz#1609]
## Description

It would be nice to be able to drag some nodes around for clarity, especially when exporting the visualization to a static PNG.

Also, maybe add a "left-to-right" auto layout? (Since most ETL/ELT diagrams I've seen are left-to-right - although of course this might have obvious cultural reasons)

## Context
A user this week told me

> "kedro viz is amazing, being able to see the layers, the functions, being able to see the entire structure of the project in a moment"

but

> "I don't know if there is a way to sort the nodes in Kedro Viz"

## Possible Implementation
Orchest had an "automatic layout" button you could use, but otherwise you were free to arrange nodes on a canvas: https://github.com/orchest/orchest/

![image](https://github.com/kedro-org/kedro-viz/assets/316517/b0ea4e37-0387-45b5-a741-612bdb9531ba)

**Comment by tynandebold** [comment]
> "I don't know if there is a way to sort the nodes in Kedro Viz"

What exactly did they mean by this? Sort them how or by what? Did they say anything more specific about what they'd like to see or be able to do?

**Comment by astrojuanlu** [comment]
Forgot to add, this was after talking to the author of https://github.com/pablovdcf/TFM_HADO_Cares cc @pablovdcf

**Comment by pablovdcf** [comment]
Hi all,

It seems to get tangled with each kedro viz and randomly generated (not sure) but for example, in the preprocessing pipeline I don't see that I can sort the DataFrame inputs and then they can be intertwined in the following steps.
![image](https://github.com/kedro-org/kedro-viz/assets/113723139/20a466de-f14a-4c63-8f06-a395a08d1487)

I have no complaints about this part because it works the same way, but when displaying several processes horizontally you can't see many interlaced lines between steps.

Thank you very much

Translated with www.DeepL.com/Translator (free version)

**Comment by rashidakanchwala** [comment]
Closing this issue as I have created two specific issues related to the above - #2159, #2160

**Comment by astrojuanlu** [comment]
Plus the one we already had #2057
