### ISSUE TITLE
Publish and share modal does not appear when on experiment tracking view

### ISSUE THREAD

**Issue by ravi-kumar-pilla** [kedro-org/kedro-viz#1633]
## Description

The publish/share modal does not get displayed when the user is on experiment tracking view (/experiment-tracking).

![Image](https://github.com/kedro-org/kedro-viz/assets/87735534/daf22b3a-2a7f-41aa-ae35-5a0689acc810)

## Context

Use the Publish and share feature when on experiment tracking view

## Steps to Reproduce

1. Go to https://demo.kedro.org/experiment-tracking
2. Click on Share and publish icon on the side nav, nothing happens
3. Go to flowchart view by clicking on flowchart icon on the side nav, the publish/share modal appears

## Expected Result
If publish/share icon is clicked, the modal should appear irrespective of the view (flowchart or experiment tracking)

## Actual Result
When publish/share icon is clicked, the modal does not appear on the experiment tracking view but appears on the flowchart view

## Your Environment
Include as many relevant details as possible about the environment you experienced the bug in:

* Web browser system and version: Chrome 119
* Operating system and version: macOS Ventura (v13.6.1)

## Checklist
- [x] Include labels so that we can categorise your issue

**Comment by rashidakanchwala** [comment]
hey Ravi, i think the 'Publish and Share' modal should not show on experiment tracking view. So we should ideally hide it because we can only Publish flowchart at the moment. @stephkaiser - can you confirm?

**Comment by stephkaiser** [comment]
hey both, thanks for flagging this Rashida 🙂 and good catch Ravi! 

You are correct that currently users can only share the flowchart view at the moment, however we want to expand on this in the future so that when a user shares kedro-viz, it shares the same viz they see in local (this is what users expect). And because sharing kedro-viz is a global action (the button is on the main navigation), the modal should appear irrespective of the view (flowchart or experiment tracking). I believe we communicate what is currently included when a user shares kedro-viz in the docs. 

I hope that clears things up! let me know if you have any further questions
