### ISSUE TITLE
Disable experiment tracking and publishing for static build

### ISSUE THREAD

**Issue by sbrugman** [kedro-org/kedro-viz#1813]
## Description
When serving a project statically via `kedro viz build`, I would like to turn off unused features:

- Experiment Tracking
- Publish and Share pipeline
- Autoreload

## Context
Why is this change important to you? How would you use it? How can it benefit other users?

## Possible Implementation
(Optional) Suggest an idea for implementing the addition or change.

## Possible Alternatives
(Optional) Describe any alternative solutions or features you've considered.

## Checklist

- [x] Include labels so that we can categorise your feature request

**Comment by astrojuanlu** [comment]
Hi @sbrugman, thanks for opening this issue. Another comment by @datajoely in a similar vein:

> As a user of the react component I want to disable both left and right sidebars since I intend to use this as an embedded element with a narrow viewport.

You might be aware that we're considering dropping experiment tracking altogether #1624 

Having said that, this goes a bit beyond exp tracking, because you also mentioned other features you want to turn off. So let me share my thoughts about what you describe here.

There's two ways to look at this feature request: additive or subtractive.

- Subtractive: Kedro-Viz, minus XYZ (this issue)
- Additive: Only the flow chart, plus potentially XYZ. Related: #1745, #1744, #1668 (already closed, but with leftover ideas)

I am personally much more interested in "progressive enhancement" and modularity than in "graceful degradation".

**Comment by rashidakanchwala** [comment]
Currently hosted shareable-viz doesn't have any of the options you list actually. So I am a bit confused 

<img width="1912" alt="Screenshot 2024-03-19 at 11 35 18" src="https://github.com/kedro-org/kedro-viz/assets/37628668/b7e4fc13-7ddd-47d0-9474-381b70f0f420">

**Comment by rashidakanchwala** [comment]
@sbrugman -- can u clarify a bit more?

**Comment by sbrugman** [comment]
Latest release shows  the experiment tracking:

<img width="217" alt="Screenshot 2024-04-11 at 11 52 27" src="https://github.com/kedro-org/kedro-viz/assets/9756388/c2b3f802-ce7d-4eaa-affc-a7ee43db38a9">

```shell
kedro viz run
```

kedro-viz 8.0.1
python 3.10
kedro, version 0.19.2

**Comment by rashidakanchwala** [comment]
interesting, are you trying to run this locally?? Our current checks in Kedro-Viz involve disabling Experiment Tracking and the Publish and Share pipeline when it detects that Kedro-Viz is not running locally but is hosted

**Comment by astrojuanlu** [comment]
> I've tried installing from source using:

This is the topic of https://github.com/kedro-org/kedro-viz/issues/1611

**Comment by astrojuanlu** [comment]
See also https://github.com/kedro-org/kedro-viz/discussions/1943

**Comment by rashidakanchwala** [comment]
@sbrugman -- anything on above?

**Comment by rashidakanchwala** [comment]
Closing this as for now. If you have any comments, let us know and we can reopen and look into it again.
