### ISSUE TITLE
Ability to retrieve hosted shareable viz url

### ISSUE THREAD

**Issue by stephkaiser** [kedro-org/kedro-viz#1851]
## Description
Currently after users publish kedro-viz and retrieve a hosted url, users need to save this link somewhere outside of kedro-viz otherwise the published url is lost, unless users are able to locate it within their hosting provider like in the AWS console. Another work-around is users can redeploy each time to retrieve a new hosted url again. To avoid this pain point for users, how might we provide users with the ability to retrieve the hosted url they have already generated? 

## Possible Implementation
A suggestion would be to save a published url within kedro-viz and provide users the option to 1) retrieve the hosted url, or 2) redeploy and retrieve a new hosted url if they have new updates to publish. 

@stephkaiser to brainstorm and provide design recommendations.

**Comment by Huongg** [comment]
another idea we can add is somewhere to store the sharable URL in the UI so user can easily copy and paste.

I sometimes have to re-publish everything, or have to go to AWS console to get the URL link.

**Comment by Huongg** [comment]
@stephkaiser do you mind sharing the design for this please ( i couldnt see it in the ticket you shared). If it's something we can get it done quickly, perhaps it will be a quick win. 

cc @rashidakanchwala @astrojuanlu

**Comment by stephkaiser** [comment]
@Huongg you can find the latest designs here - https://www.figma.com/file/3kSpvIO1veLKfy9qHxuXwF/Kedro-WIP?type=design&node-id=1411-87299&mode=design&t=bSwcXxbq95GPPfud-4

TBC items discussed:
- Huong to investigate if it's possible to save form information so users don't need to complete the form again after the first time
- Huong to investigate if it's possible to find out if a published url is outdated so we can let users know their published link is outdated to their current version
- Steph to create Endpoint tooltip

**Comment by Huongg** [comment]
Hi @stephkaiser, I've discussed this further the engineering team in kedro-viz today. Here is a quick summary of what we discussed:

**Is it possible to save form information so users don't need to complete the form again after the first time?**

- Yes it is possible. We will store the fields ncluding hosting platform, bucket name and endpoint URL in [localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) once the user publishes it
<img width="836" alt="Screenshot 2024-04-22 at 18 51 30" src="https://github.com/kedro-org/kedro-viz/assets/32060364/1fa01ca5-ff93-47e4-866f-be3cb57e1399">

- We discussed whether we should display the timestamp in the shareable URL popup modal as well, and the answer is no, as it can be misleading if the user clears the browser or opens multiple ones.
- Further technical question TBD later: should we store the cloud provider key or timestamp in localStorage?
- Further design question: What happens if a user publishes on more than one hosting platform? This might be a very edge scenario unlikely to happen, but worth considering. If there's any quick way we can address this with a simple design (e.g., dropdown), it can be a quick change


**Is it possible to find out if a published url is outdated so we can let users know their published link is different to their current version?**

- We think this is a good idea however it requires heavy technical effort, so we think it is best to see if any more users suggest this feature, so we can increase the weighting of it. Happy to discuss further. 
- Below is the potential suggestion for this feature
<img width="1013" alt="Screenshot 2024-04-22 at 21 02 45" src="https://github.com/kedro-org/kedro-viz/assets/32060364/64763a50-2e10-4868-8367-415c46e2ef81">


cc @astrojuanlu @rashidakanchwala

**Comment by stephkaiser** [comment]
thanks @Huongg! 

For your comment on saving form information, that sounds good to me!

> Further design question: What happens if a user publishes on more than one hosting platform? This might be a very edge scenario unlikely to happen, but worth considering. If there's any quick way we can address this with a simple design (e.g., dropdown), it can be a quick change

On the above^, this is a good point and definitely worth considering. I will make minor tweaks to the designs so we can cover this scenario as well. 

For the second topic on: _**Is it possible to find out if a published url is outdated so we can let users know their published link is different to their current version?**_

This was actually one of the most requested feature when I did usability testing for shareable viz, almost every user I tested with asked for this so we do have good evidence that there is a user need. Since it's a large technical effort, let's discuss potential ways we can make this smaller in scope - for example, we don't need a comparison here just a signal to users that it's time for them to republish as their current link is outdated. Not sure if this is still quite complex or not but lets discuss and see what is possible :) Also we can open a separate ticket for this topic as well if it requires further investigation

cc @rashidakanchwala

**Comment by stephkaiser** [comment]
Hey @Huongg, I've updated the designs now to include a design for when a user publishes on more than one hosting platform, and I also added a Endpoint url tooltip - https://www.figma.com/file/3kSpvIO1veLKfy9qHxuXwF/Kedro-WIP?type=design&node-id=1411-87299&mode=design&t=bSwcXxbq95GPPfud-4

Let me know what you think :)

**Comment by stephkaiser** [comment]
I've created a separate ticket for: **Is it possible to find out if a published url is outdated so we can let users know their published link is different to their current version?**

here - https://github.com/kedro-org/kedro-viz/issues/1890

**Comment by Huongg** [comment]
thank you very much @stephkaiser. I've left a few comments/questions in the design file btw. Let me know if you want to discuss them quickly on a call?
