### ISSUE TITLE
Enable users to disable preview for all when publishing Kedro-Viz

### ISSUE THREAD

**Issue by ravi-kumar-pilla** [kedro-org/kedro-viz#1870]
## Description

This would help users to enable/disable preview for all the datasets.

## Context

* Users would like to have preview enabled in the catalog or for `kedro viz run` locally, but would like to disable the preview for all the datasets when deploying to cloud providers

https://kedro-org.slack.com/archives/C03RKP2LW64/p1713469330441069

## Possible Implementation

* Introduce a `--include-preview` option for all kedro viz cli commands
* Default the preview feature to False (need to be discussed)

## Checklist

- [x] Include labels so that we can categorise your feature request

**Comment by rashidakanchwala** [comment]
had a Design PS session with Ivan, Yetu, and Steph. The following came out of discussion 

instead of `include_preview` or `exclude_preview` we simply have preview=true/false 

- Instead of using --include-preview or --exclude-preview, we'll switch to --preview=false/true.
- By default, kedro viz deploy and kedro viz build will set --preview=false.
- On the other hand, kedro viz and kedro viz run will set --preview=true by default.
- In the UI, users will specify whether they want to Enable or Disable preview before publishing. The backend will then create a JSON API both with and without preview based on the user's selection.

**Comment by stephkaiser** [comment]
Designs can be found here - https://www.figma.com/file/3kSpvIO1veLKfy9qHxuXwF/Kedro-WIP?type=design&node-id=1411-87299&mode=design&t=HEcOS0koRJ2SVfbX-4
