### ISSUE TITLE
How to open Kedro viz build folder locally?

### ISSUE THREAD

**Issue by noklam** [kedro-org/kedro-viz#1918]
## Description
Is your feature request related to a problem? A clear and concise description of what the problem is: "I'm always frustrated when ..."

I have a request from user which need to share viz with 0 infrastructure. At the end I recommend just using `kedro viz build` and open the `index.html` directly. My impression is that I can open the index.html, but it doesn't work as I get a kedro-viz UI but things are not loaded properly. Maybe the it's a routing issue similar to the sub-path?
<img width="1682" alt="image" src="https://github.com/kedro-org/kedro-viz/assets/18221871/51069cd5-cf95-4a36-b005-b1e8431db733">

I recalled I can do this with `sphinx doc build`. At the end I have to use the vscode extension "Live Server` and open `index.html` with it, so it's a mini web server running behind.

Questions:
- Is it possible to open it without a web server?
- If so, what are the steps?

**Comment by astrojuanlu** [comment]
Previously reported at https://github.com/kedro-org/kedro-viz/issues/1721#issuecomment-1916410936

**Comment by jitu5** [comment]
Currently, attempting to run `kedro-viz` by simply opening `index.html` through the `file://` protocol causes CORS issues. Most modern browsers enforce strict CORS policies for local files to prevent security vulnerabilities.

The issue is inherently linked to browser-level security, not something that can be resolved purely by modifying the frontend code or server configurations. Changing browser CORS behavior from the JavaScript side or embedding special headers is not possible when using `file://` due to the restrictions set by browser for security reasons. 

Therefore, the recommendation for a proper user experience is to run `kedro-viz` using a local web server, which avoids CORS policy issues and guarantees that all resources are correctly served and accessed. Examples of lightweight static servers include Python's `http.server` or Node.js `http-server`, which can easily serve the generated HTML.

I will update existing [documentation](https://docs.kedro.org/projects/kedro-viz/en/stable/platform_agnostic_sharing_with_kedro_viz.html) of `kedro viz build` to highlight right way to use build folder.

**Comment by astrojuanlu** [comment]
To note, a user complained last week that lack of "double click" open was a limitation for them. So, although we've documented why this is not currently possible in #2126 👍🏼 I think we should keep an eye on this and, if we notice more people are affected, try reworking the output of `kedro viz build` so that it's not affected by CORS.
