### ISSUE TITLE
Kedro PR will break parameters in kedro-viz

### ISSUE THREAD

**Issue by bpmeek** [kedro-org/kedro-viz#1933]
## Description
If [PR](https://github.com/kedro-org/kedro/pull/3905) is merged, it will affect the behavior of showing `parameters` in kedro-viz

## Context
The unpacked parameters won't show up, nor will the parent dictionary

## Steps to Reproduce

1. Create the example project using `kedro new`
2. Change `pipelines/data_science/nodes.py`, `pipelines/data_science/pipelines.py` as shown in the ticket
3. Start kedro-viz
4. Select the option to show parameters

## Expected Result
Either the unpacked dictionary or the entire entry should show

## Actual Result
Nothing

```
-- If you received an error, place it here.
```

```
-- Separate them if you have more than one.
```

## Your Environment
Include as many relevant details as possible about the environment you experienced the bug in:

* Web browser system and version: Chrome 125.0.6422.113
* Operating system and version: MacOS 14.5
* NodeJS version used (if relevant): 
* Kedro version used (if relevant): Referenced in PR
* Python version used (if relevant): 3.10.14

## Checklist
- [X] Include labels so that we can categorise your issue

**Comment by astrojuanlu** [comment]
Hi @bpmeek , we're slowly catching up with backlog items, sorry about our slow response.

I'm not up to date with https://github.com/kedro-org/kedro/pull/3905 but my understanding is that Kedro-Viz, as consumer of Kedro, shouldn't break - otherwise that would be a sign of a breaking change, that should not have happened until the next Kedro release, 0.20.*.

In other words, the PR should be backwards compatible.

The heads up is appreciated 🙏🏼 but for now there's nothing for us to do here.
