### ISSUE TITLE
URL Access to Experiment Tracking Causes 404 Error on viz demo

### ISSUE THREAD

**Issue by SajidAlamQB** [kedro-org/kedro-viz#2048]
## Description
When accessing the experiment tracking page directly via the URL https://demo.kedro.org/experiment-tracking, a `404` error is returned. This issue only occurs when accessing the page directly via the URL, while navigation through the site’s tabs works as expected.

## Context
This bug affects our ability to access the experiment tracking page directly via a URL, which is important for user experience and ease of access.

## Steps to Reproduce

- Attempt to access the experiment tracking page directly by visiting https://demo.kedro.org/experiment-tracking.
- See the `404` error.

## Expected Result
The experiment tracking page should load.

## Actual Result
<img width="1728" alt="image" src="https://github.com/user-attachments/assets/9acef439-8f5f-4fa7-bc79-d8cdf03a7a80">

## Checklist
- [x] Include labels so that we can categorise your issue

**Comment by ravi-kumar-pilla** [comment]
Some Context:

GitHub Pages doesn’t support routers that use the HTML5 pushState history API under the hood (for example, React Router using browserHistory). This is because when there is a fresh page load for a url like http://user.github.io/todomvc/todos/42, where /todos/42 is a frontend route, the GitHub Pages server returns 404 because it knows nothing of /todos/42.

Possible solution:

More information and possible solutions are mentioned here - https://create-react-app.dev/docs/deployment/#github-pages

Thank you
