### ISSUE TITLE
[FE] Make dotted datasets clickable and hoverable when in focus mode

### ISSUE THREAD

**Issue by tynandebold** [kedro-org/kedro-viz#750]
(transfer from Jira, created by @datajoely)

If you look at the image below, you can't click the dotted plotly nodes.

![screenshot-1](https://user-images.githubusercontent.com/16869061/155153817-8fba9a5f-2bf3-46a5-9f34-925a58de4d27.png)

Team thoughts:

- What does the user expect when you click on one of the dotted nodes?
- Is there an appetite to click on these nodes and see the context, e.g., in the metadata panel?
- Is this a common struggle?
- From a design perspective, how do we best indicate that you're in the ghost state?

**Comment by studioswong** [comment]
Thanks for migrating this @tynandebold 👍 
It seems like this issue is a ticket migrated from Jira - It might be great to include a mention of where this issue originate from within the description for better context ( something like  'this ticket is migrated from KED-XXXX filed by @xxx'  as how the core team did when they migrated the issue.)

Thank you!

**Comment by tynandebold** [comment]
Acceptance criteria:
- You should be able to click on these dotted datasets when in focus mode, and when doing so it should open the metadata panel
- You should be able to hover over them and see a tooltip
