### ISSUE TITLE
[FE] Inconsistent highlight state for input/output nodes in the sidebar

### ISSUE THREAD

**Issue by tynandebold** [kedro-org/kedro-viz#751]
(transfer from Jira, created by @studioswong)

Under focus mode, the input and output nodes relating to the selected modular pipeline should not be highlighted (see below). 

![image-2022-01-18-09-36-35-645](https://user-images.githubusercontent.com/16869061/155161037-c5c36ffe-b885-4ae8-aea3-b3dfe9711d0b.png)

Some output nodes for the 'train evaluation' pipeline were in a highlighted state (see below). The input nodes stays in the intended non-highlight state. 

Having tested around this project it seems that this highlighted state is unique to those nodes as pictured - this is likely due to an edge case / minor bug introduced from the collapsed modular pipeline calculations. 

![image-2022-01-18-09-32-26-535](https://user-images.githubusercontent.com/16869061/155161077-5b38bcb0-011e-44a9-974a-e6a8c0d3d480.png)

**Comment by Huongg** [comment]
hey @tynandebold after inspecting the code and suggestion from @rashidakanchwala , the issue seems to be from the data side, as in those 4 highlighted fields should be children of `TrainEvaluation` but when it's actually not when I logged it, hence it renders as `renderLeafNode(child.data);` rather than as part of the `renderTree(tree, child.id)`

**Comment by Huongg** [comment]
I don't think it can be fixed from the FE side

**Comment by tynandebold** [comment]
Yeah, probably not. Thanks for confirming. I'll add a `python` label.

I'm not sure what we're aiming to achieve here though, as the text copied from Jira isn't so clear. When in focus mode, should those nodes be highlighted same as the modular pipeline we're focusing on? Or are we saying that they shouldn't appear at all?

@AntonyMilneQB do you know?

**Comment by AntonyMilneQB** [comment]
I _think_ the problem described here refers just to the sidebar here rather than the main flowchart view. If you look at the second picture you can see the output datasets are highlighted when they should stay non-highlighted (like the inputs remain). I don't know whether this highlighting has implications for anything else other than how the text appears in the side bar though.
![image](https://user-images.githubusercontent.com/49395058/192231374-c5604263-2ecc-445d-8312-f61e5c176058.png)

**Comment by tynandebold** [comment]
Understood!

**Comment by rashidakanchwala** [comment]
> I _think_ the problem described here refers just to the sidebar here rather than the main flowchart view. If you look at the second picture you can see the output datasets are highlighted when they should stay non-highlighted (like the inputs remain). I don't know whether this highlighting has implications for anything else other than how the text appears in the side bar though. ![image](https://user-images.githubusercontent.com/49395058/192231374-c5604263-2ecc-445d-8312-f61e5c176058.png)

@AntonyMilneQB  -- it's not just that the highlight state, but also these nodes should be a part of the modular pipeline so within the tree structure but they r outside the tree
