### ISSUE TITLE
[BE] Clean up experiment tracking viz code after `session == run` decision

### ISSUE THREAD

**Issue by MerelTheisenQB** [kedro-org/kedro-viz#764]
## Description
If a user is in an interactive workflow (e.g. ipython or jupyter), uses the `SQLiteStore` to record a session and then spins up `kedro viz`, the graphql endpoint will fail to fetch data because of an assumption that the user is in a `CLI` workflow: 
https://github.com/kedro-org/kedro-viz/blob/main/package/kedro_viz/api/graphql.py#L81

## Solution
Instead of throwing an error we should make this a `.get()` call and just set `None` for the CLI command. In general it's better to have a `.get()` call to fetch elements from a python dict in case the item isn't there like we do here: https://github.com/kedro-org/kedro-viz/blob/main/package/kedro_viz/api/graphql.py#L77 

## Checklist
- [ ] Include labels so that we can categorise your issue

**Comment by AntonyMilneQB** [comment]
From discussions with @MerelTheisenQB, this task should also include tidying up the various different `session_id`/`run_id`/`timestamp` fields. This follows the changes in https://github.com/kedro-org/kedro/issues/1273, which remove the concept of a `run_id` (it's the same as the `session_id`).

This includes the following, although there might be additional tasks too:

* always use the session store `runs.id` in preference to `runs.blob["session_id"]` (they will always contain the same thing, but let's be consistent), e.g. [here](https://github.com/kedro-org/kedro-viz/blob/main/package/kedro_viz/api/graphql.py#L82)
* understand how `timestamp` is used - if only on the frontend as an immutable field then we can just remove this field altogether (it's not present in the database) and use `runs.id` instead
* remove the comment from [here](https://github.com/kedro-org/kedro-viz/blob/main/package/kedro_viz/data_access/repositories/runs.py#L84) - there's not going to be a `timestamp` field; we'll just use `id` as it currently has
* be clear and consistent with terminology session vs. run. Possibly rename the `runs` table to `sessions` - but for consistency this would also mean renaming everything that is `run_xyz` to `session_xyz` instead; probably easiest just to leave the names as `run` throughout and document somewhere that a kedro viz run = kedro session, and don't use "session" in kedro viz at all
* check what happens if a user saves a session from `kedro jupyter` (by calling `session.close()`) _without doing a run_ - does this appear in experiment tracking [ideally it shouldn't]? Does it break stuff?

**Comment by limdauto** [comment]
This sounds good to me. In retrospect, the session -> multiple runs have never really gotten a solid use case from a real user. Also happy with the fact that `run_id` is deprecated. 

Regarding equating ID to timestamp and setting that in stone, I'm trying to remember the use case where people want to provide a custom run format, but all I could think of was PAI monkey patching the `get_run_id` method. Can't think of a real use case. I was also anticipating the use case where we want to deploy Kedro-Viz with a persistent database then using timestamp as the primary key might not be the most efficient. But I guess we can always add another column called `pk` with an autoincrement value, so might be a non-problem.

**Comment by AntonyMilneQB** [comment]
Great, thanks for the comments @limdauto.

Related to the primary key actually, I have a stupid question... is there a good reason we have an `id` column in the `user_run_details` table? Is this just good practice or some technical constraint or actually used for something? (There's no other column in that table that can act as primary key)

**Comment by limdauto** [comment]
@AntonyMilneQB actually `run_id` could be a primary key for that table if it's an one-to-one mapping. The `id` column is not used at the moment, just us blindly following a convention. Could be an interesting candidate to test out the migration mechanism.
