### ISSUE TITLE
Save file sorting code can cause issues if keys aren't all strings

### ISSUE THREAD

**Issue by datajoely** [kedro-org/kedro-viz#794]
## Description
> Short description of the problem here.

User reported the following error:

```
    run_server(**run_server_kwargs)
  File "/miniconda/envs/customerone/lib/python3.7/site-packages/kedro_viz/server.py", line 88, in run_server
    Path(save_file).write_text(res.json(indent=4, sort_keys=True)) <-------------ERROR here
  File "pydantic/main.py", line 490, in pydantic.main.BaseModel.json
  File "/miniconda/envs/customerone/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  ...
    items = sorted(dct.items(), key=lambda kv: kv[0])
TypeError: '<' not supported between instances of 'str' and 'bool'
kedro.framework.cli.utils.KedroCliError: '<' not supported between instances of 'str' and 'bool'
Run with --verbose to see the full exception
Error: '<' not supported between instances of 'str' and 'bool'
```

This is the offending logic. Having checked with @limdauto this was introduced to ensure that you get the same JSON file every time:

https://github.com/kedro-org/kedro-viz/blob/39524c0f6d323775d891527eea276aa563b3be7f/package/kedro_viz/server.py#L86

## Context
> How has this bug affected you? What were you trying to accomplish?

@musabilal  reported this issue, my hypothesis is that this was caused by boolean key in some YAML configuration within the project. We weren't able to prove this, but we were able to prove that if we removed '`sort_keys=True`' it would work.

## Steps to Reproduce

I think (but wasn't able to prove) doing parameters like this + trying to save JSON will cause the sort error:

```yaml
true: some string
```

## Expected Result
>Tell us what should happen.

JSON exported to disk

## Actual Result
>Tell us what happens instead.

⬆️ Stack trace above

## Proposed solution:

```python
try:
   Path(save_file).write_text(res.json(indent=4, sort_keys=True)) 
except TypeError:
   Path(save_file).write_text(res.json(indent=4, sort_keys=False)) 
```

**Comment by AntonyMilneQB** [comment]
Thanks for the excellent investigation and bug report @datajoely! I can confirm that this is a problem caused by having a parameters file with keys of different types - even just one integer key + one string key will break it.

It's not a problem in the metadata panel because things appear to be stringified there. Not quite sure why keys are strings there but not when we do `save-file` - will need to check to see what the best solution is here.
![image](https://user-images.githubusercontent.com/49395058/160098620-f2a40217-3563-49e9-803d-b599c4ac34ff.png)


![image](https://user-images.githubusercontent.com/49395058/160098217-f931d459-d0c2-4316-bf2f-8d620af4d353.png)

**Comment by rashidakanchwala** [comment]
@AntonyMilneQB  - i think the sort keys doesn't make much difference here. from the looks of it, it only sorts the top level keys -- see below unsorted and  sorted json (left->right)

![Image](https://user-images.githubusercontent.com/37628668/183403389-47e7135f-019b-4618-9a3a-9bb79a2f57f9.png)
