### ISSUE TITLE
[KED-3079] [FE] Change runsList route name to something more appropriate

### ISSUE THREAD

**Issue by tynandebold** [kedro-org/kedro-viz#819]
(transfer from  Jira, created by @tynandebold)

Having [runsList](https://demo.kedro.org/runsList) as the URL route for experiment tracking seems like a poor choice. Let's change it to `/experiment-tracking` or something along those lines.

Kedro core reference: https://kedro.readthedocs.io/en/stable/08_logging/02_experiment_tracking.html

**Comment by datajoely** [comment]
@NeroOkwa this will break your Heap dashboard FYI

**Comment by studioswong** [comment]
FYI the context behind using `runsList` instead of `experiment-tracking` stems from the previous comments we got in refraining from using `experiment-tracking` to describe this feature and instead to describe each experiment as a `run` when setting up the routes. 

That said, throughout all documentation and in looking at how this feature is referred to now, it's a valid consideration and a very small change regardless.

**Comment by studioswong** [comment]
follow up: @datajoely Nero and I had a look at the dashboard, one thing to note about this route name change - we might lose the heap metrics of the users who have not updated to the latest version ( i.e those who are accessing the experiment tracking features via the route name `/runsList` )  if we only track via the `experiment-tracking` route. It might be worth to add in both `runsList` or `experiment-tracking` routes just so we can capture the metrics for users on both the older and latest versions of Kedro-Viz.

**Comment by datajoely** [comment]
Yeah we can fix it fine - heap allows you to combine events, I was just tagging Nero so he was aware we have to make the change when this gets released.

In general I'd like more information in the URL / title since Heap tracks that well and we could do a lot with that :)
