### ISSUE TITLE
Expand namespaced pipeline by double clicking

### ISSUE THREAD

**Issue by marcosfelt** [kedro-org/kedro-viz#874]
## Description
I would like to be able to open namespaced pipeline by double clicking on it the pipeline flowchart.

![Screen Shot 2022-05-30 at 4 34 11 PM](https://user-images.githubusercontent.com/25933639/171024514-14e6aab7-b7b4-478e-950d-e48b14804e55.png)

## Context
This is just a small enhancement to make digging into pipelines faster.

## Possible Implementation
Not sure, but if someone gives me a pointer, I would be happy to do it!

## Possible Alternatives
Perhaps a keyboard shortcut? I definitely think the mouse click is more useufl.

**Comment by limdauto** [comment]
@tynandebold hmm I actually think this one is quite simple to do. 1s let me make a branch

**Comment by AntonyMilneQB** [comment]
Thank you so much for raising this @marcosfelt! It's my number 1 feature request for kedro-viz also so I'm pleased I'm not the only one who wants it 😀

Just to note something here for completeness: when this has been discussed in the past, one question has been how/whether you should be able to reverse the expand operation in the flowchart (i.e. not using the sidebar). The problem of course is that once you've expanded the namespaced pipeline, it no longer appears on the flowchart so it's not obvious what you would click to collapse it back again. 

In my opinion it's not a big issue and I would be VERY happy to be able to expand pipelines out directly from the flowchart. It's just a bit inconsistent because we can't (yet?) collapse them back the same way.

**Comment by tynandebold** [comment]
Hey @marcosfelt, we've now completed the work for this! It'll be a single-click to expand initially, and then we'll go from there, based on user feedback and other related items in the roadmap. This behavior will be available in the next release, which should happen end of next week.

Thanks again for raising this in the first place! Hope to see you contribute again in the future.

**Comment by marcosfelt** [comment]
Thank you so much!! Looking forward to trying it out :)
