### ISSUE TITLE
Consolidate current colour variables and styles

### ISSUE THREAD

**Issue by comym** [kedro-org/kedro-viz#949]
We're revisiting all colour variables currently used on Viz and consolidating them all into new styles as part of our design system.

After having it done on the design side, the idea is to team up with engineering and see how we can simplify/unify/clean up the multiple colour variables we have accumulated over the years.

![Image](https://user-images.githubusercontent.com/55446576/177139583-7c28923b-4071-43d3-a2e2-96e12b24439a.jpg)

**Comment by GabrielComymQB** [comment]
Hi team, 

I'm putting this into review for now. It's infinite work but I guess I've gathered all the colours we're using at the moment.

Here we have it
https://www.figma.com/file/akJ7QasxvLcgqc8Hxud7QB/Kedro-Design%3A-OUT?node-id=319%3A16363


![Image](https://user-images.githubusercontent.com/55446576/178021304-531367c0-ee52-4450-9be6-502dad002c7e.jpg)


As we go, please let me know if we find any other colours we've missed or any other mysterious colour blends we have to address.

I'm happy to regroup with engineering at any point to talk about these.

In this frame, you'll notice I'm also marking some colours. There are two main important types:

![Image](https://user-images.githubusercontent.com/55446576/178020279-25b2cccc-41c7-4575-aadc-03e961d4bcc9.jpg)

These are colours that we need to double-check the HEX value, either because we found to be inconsistent or because it was difficult to verify this variable using the inspector.


![Image](https://user-images.githubusercontent.com/55446576/178020466-76a75ffa-5adf-4911-a0c8-1919d6ad9c01.jpg)

The ones marked with DD are colours that we already know will be part of a Design Debt ticket soon. These colours do not show the right values in the current build.


This is it, please have a look and let me know if you have any questions.


Many thanks
