### ISSUE TITLE
Research: Viz usage as a React component

### ISSUE THREAD

**Issue by tynandebold** [kedro-org/kedro-viz#954]
## Description

We'd like to know how many users are using Viz as a [React component](https://www.npmjs.com/package/@quantumblack/kedro-viz). 

## Context

Do we need to continue supporting this use case?

## Outcome

An answer to the question above.

## Checklist

- [x] Include labels so that we can categorise your feature request

**Comment by tynandebold** [comment]
On 5 July, 2022, the following question was posed to the appropriate users channels in Discord and Slack:

> Hello, everyone! We're looking to understand your usage of Kedro-Viz. Specifically, do you use it as a React component? https://www.npmjs.com/package/@quantumblack/kedro-viz
> 
> 👍 for yes, 👎 for no

After ~48 hours, we have:

- Six no answers 
- Four yes answers from
  - Nikos, Nab, @datajoely, Tobias

It's also thought that these two products might be using Viz as a React component:
- https://tokern.io/data-lineage/
- https://realityfold.com/ (@921kiyo)

Next step: follow up with each positive (yes) response, plus the two products linked above, and as them about how they're using Viz. Specifically:
- What features they're using?
- What features they're not using?
- Do they need any interactivity?
- Would you be interested in a version of Viz that _only_ displays the Flowchart (a.k.a. pipeline visualization) and nothing more?
- ...

**Comment by 921kiyo** [comment]
@tynandebold Thank you for tagging me! I am not using Viz as a React component, I just used the Viz pipeline image in my website (sorry for the confusion...)

**Comment by tynandebold** [comment]
No confusion! Thank you for clarifying :)

**Comment by tynandebold** [comment]
Great context @datajoely, thank you.

Some thoughts and questions:
1. When you say, "This is where the React component would be start" do you mean **_if_** we had Viz a React component?
1. For your medium article, why didn't you use the `export` functionality of Viz and then add those output images to your article? Did you want the embed to be interactive? Your article was all about "layered thinking" and thus you showed and referenced the layers in Viz. The image exports don't actually include those, though if they did, would you have used them?
1. We do actually have this: `Viz component + JSON = Visualization.` That's our React component. Perhaps that isn't ideal, as you need to create a small standalone application to get the output. Instead, and still using your formula, what if we output a standalone and single HTML file with the necessary CSS and JS included to display the Visualization? Would that be better and more usable? Could you have used that in Medium? Or even in a GitHub readme?
1. For use in Docs, I think the image output of Viz is feasible, though maybe not feature rich right now? We have a feature request from a user (#638) where they mention they'd like a way to programmatically export/save the visualization for exactly this reason ("automatic documentation updates"). We're thinking about how to do this now.

**Comment by studioswong** [comment]
Hi folks - nice discussion! joining in the fun with my 2 cents here. 

@tynandebold to your second and third point, my understanding is that @datajoely wants to showcase the interactive kedro-viz pipeline using medium embeds via a glitch hosted link (see [this article](https://medium.com/@asameshimae/using-glitch-to-embed-apps-in-medium-e21bc50a388c)). I had a brief look at embedding and rendering an html file as an embed in medium and don't think Medium supports it natively - i.e doing so will still require you to upload and host the html file somewhere which is probably the same amount of effort as setting it up as a react component export.

My curiosity is - what is the reason to _not_ support the react component usage? It might seem counter-intuitive to look into setting up a new function to export and output a standalone HTML file in kedro-viz rather than utilizing the npm export setup which we have already setup nicely within our CI pipeline. There are other QB products who are consuming kedro-viz via npm ( such as Brix) - does stopping the npm support means they won't get the new goodies from latest versions of kedro-viz?

In terms of the the user request from #638 , to me it seems like a different use case as it looks like the user just wants a fast way to export svg/png directly via the terminal rather than via the Kedro-Viz UI, which is an entire different use case from those who consumes kedro-viz via an npm component ( which most likely they utilize it to showcase the interactive flowchart)

**Comment by datajoely** [comment]
@tynandebold 

1. Yes I mean, IF we had it, we could potentially do some cool things.
2. My thinking is that a when describing a complex pipeline the ability to interactively fold and interrogate is super useful and better than any static image.
3. For Medium you need to use one of their accredited embed providers - Ideally I would have used Codeopen to just pass the JSON to a component and it would work fine. In this case I needed to do a much more involved process to get Glitch working. 
4. I think this is the same point as 2, we can do static images fine - interactivity is the exciting part.

**Comment by tynandebold** [comment]
@studioswong thanks for chiming in!

> My curiosity is - what is the reason to not support the react component usage?

The short answer is to reduce complexity of the app in tandem with reducing the workload when building some potential future features.

> There are other QB products who are consuming kedro-viz via npm ( such as Brix) - does stopping the npm support means they won't get the new goodies from latest versions of kedro-viz?

No, we still want to support other teams using Viz while trying to determine if the way they're using it is most optimal. For the Brix case and their setup, there was no other way to use it, so they took what we offered and ran with that. Yet what if there was a more suitable alternative (e.g. a HTML-generated view of the pipeline, a Kedro-Viz-Lite NPM package only showing the flowchart, a more rich static image export, etc., etc.)? Would that have been preferable?

This are some of the things we're trying to answer.

**Comment by datajoely** [comment]
Re 1 - As a novice JS user my understanding of 3 [Codepen](https://codepen.io/) thought this wasn't valid.

**Comment by tynandebold** [comment]
You can basically import anything from NPM into CodePen. [Here's a small React app](https://codepen.io/tynandebold/pen/LYdRrYr) running in there. I've tried using Viz in here and unfortunately we get an error with one of our dependencies. If we didn't, it should work just fine.

**Comment by tynandebold** [comment]
Given the feedback from user interviews, we'll continue to support using Viz as a React component.

We should strive to better our user's experiences with things like modularity, being lighter weight, adding access to click handlers, and more.

**Comment by tynandebold** [comment]
Closing this issue as the conclusion was reached that we'll still support this use case.
